language: python
python:
  - '3.6'
services:
  - mongodb
  - docker
install:
  # TODO DONT USE THE REAL INGINIOUS VERSION AS THEY DONT MERGE THIS PR :
  # https://github.com/UCL-INGI/INGInious/pull/415
  # - pip3 install git+https://github.com/UCL-INGI/INGInious
  - pip3 install git+https://github.com/jy95/INGInious
  - docker pull ingi/inginious-c-base
  - docker pull ingi/inginious-c-default
  - docker pull ingi/inginious-c-java8scala
  # Dependencies for verification scripts
  - pip3 install -r requirements.txt
before_script:
  - python3 travis_setup.py
  - chmod +x check_requirements.py
script:
  - echo "Inginious Testing on your tasks"
  - inginious-autotest . LEPL1402 -l
  - echo "Consistence Testing on your tasks"
  - ./check_requirements.py
  - echo "Integration Testing on the generic runscript"
  - inginious-autotest . \$test\$ -l
notifications:
  slack:
      on_success: change
      on_failure: always