language: python
python:
  - '3.6'
services:
  - mongodb
  - docker
install:
  - pip3 install git+https://github.com/UCL-INGI/INGInious
  - docker pull ingi/inginious-c-base
  - docker pull ingi/inginious-c-default
  - docker pull ingi/inginious-c-java8scala
  # Dependencies for verification scripts
  - pip3 install -r requirements.txt
before_script:
  - python3 travis_setup.py
  - chmod +x check_requirements.py
script:
  - echo "Inginious Testing on your tasks + (Integration Testing on the generic runscript)"
  - inginious-autotest . LEPL1402 -l
  - echo "Consistence Testing on your tasks"
  - ./check_requirements.py
notifications:
  slack:
      on_success: change
      on_failure: change
