name: Integration Testing
on: push
jobs:
    testing:
      runs-on: ubuntu-20.04
      steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Install INGInious containers
            run: |
              sudo docker pull ingi/inginious-c-base
              sudo docker pull ingi/inginious-c-default
              sudo docker pull ingi/inginious-c-java8scala
          - name: Install INGInious
            run: |
              sudo pip3 install git+https://github.com/UCL-INGI/INGInious
          - name: Set up Testing
            run: |
              python3 travis_setup.py
          - name: Testing your tasks
            run: |
              sudo inginious-autotest . LEPL1402 -l
